<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="7" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-19T15:56:11 IST" name="Default suite" finished-at="2021-02-19T15:56:11 IST" duration-ms="159">
    <groups>
    </groups>
    <test started-at="2021-02-19T15:56:11 IST" name="Default test" finished-at="2021-02-19T15:56:11 IST" duration-ms="159">
      <class name="TestCalculate">
        <test-method is-config="true" signature="init()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="init" finished-at="2021-02-19T15:56:11 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="emptyStringReturnZer()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="emptyStringReturnZer" finished-at="2021-02-19T15:56:11 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyStringReturnZer -->
        <test-method signature="ignoresNumberGreaterThan1000()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="ignoresNumberGreaterThan1000" finished-at="2021-02-19T15:56:11 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ignoresNumberGreaterThan1000 -->
        <test-method signature="negativeInputReturnsException()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="negativeInputReturnsException" finished-at="2021-02-19T15:56:11 IST" duration-ms="2" status="PASS">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Negative input]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Negative input
at Calculator.findNegativeInputException(Calculator.java:37)
at Calculator.getSum(Calculator.java:19)
at Calculator.calculate(Calculator.java:14)
at TestCalculate.negativeInputReturnsException(TestCalculate.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeInputReturnsException -->
        <test-method signature="singleValueIsReplied()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="singleValueIsReplied" finished-at="2021-02-19T15:56:11 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleValueIsReplied -->
        <test-method signature="threeNumberDelimiterBothWaysReturnSum()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="threeNumberDelimiterBothWaysReturnSum" finished-at="2021-02-19T15:56:11 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threeNumberDelimiterBothWaysReturnSum -->
        <test-method signature="twoNumberDelimiterReturnSum()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="twoNumberDelimiterReturnSum" finished-at="2021-02-19T15:56:11 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoNumberDelimiterReturnSum -->
        <test-method signature="twoNumbersNewLineDelimiterReturnSum()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-02-19T15:56:11 IST" name="twoNumbersNewLineDelimiterReturnSum" finished-at="2021-02-19T15:56:11 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoNumbersNewLineDelimiterReturnSum -->
      </class> <!-- TestCalculate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
